import { Providers } from "./provider";
import { Inter } from "next/font/google";
import "./globals.css";
// import dynamic from "next/dynamic";
import Nav from "./Components/Navbar/Nav";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-slate-100 dark:bg-black">
        <Providers>
          {/* <DynamicNav /> */}
          <Nav/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
