import { Providers } from "./provider";
import { Inter } from "next/font/google";
import "./globals.css";

import Nav from "./Components/Navbar/Nav";
const inter = Inter({ subsets: ["latin"] });

import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";

export const metadata = {
  title: "SkillSync",
  description: "Generated by create next app",
  icons: [
    {
      rel: 'icon',
      type: 'image/png',
      sizes: '32x32',
      url: '/favicon-32x32.png',
    },
    {
      rel: 'icon',
      type: 'image/png',
      sizes: '16x16',
      url: '/favicon-16x16.png',
    },
    {
      rel: 'apple-touch-icon',
      sizes: '180x180',
      url: '/apple-touch-icon.png',
    },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
   
      <body className="bg-slate-100 dark:bg-black ">
      <link rel="icon" href="/favicon.ico" sizes="any" />
        <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
        <Providers>
          <Nav />
          {children}
        </Providers>
      </body>
    </html>
  );
}
